### ISSUE TITLE
Submit patch or minor version update to CRAN 

### ISSUE THREAD

**Issue by parmsam** [parmsam/lzstring-r#27]
To reflect bug fix in PR #26.

**Comment by pawelru** [comment]
Hey @parmsam. Did you have a chance to have a look into this?

**Comment by parmsam** [comment]
Hi @pawelru! I'll get to it this week. Thanks for following up.

**Comment by parmsam** [comment]
Had some free time today. Just resubmitted it to CRAN. I'll close this issue after it gets released.

**Comment by parmsam** [comment]
It's on CRAN now. That was quick. 
https://cran.rstudio.com/web/packages/lzstring/index.html
